/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary": "#006877",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "tertiary": "#835400",
        "primary-fixed-dim": "#2fd9f4",
        "outline": "#6c797d",
        "surface-container": "#eaedff",
        "secondary-container": "#fd761a",
        "surface-tint": "#006877",
        "surface-bright": "#faf8ff",
        "on-surface": "#131b2e",
        "surface-container-high": "#e2e7ff",
        "glass-border": "rgba(255, 255, 255, 0.4)",
        "tertiary-container": "#ffb13b",
        "surface-base": "#FFFFFF",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-background": "#131b2e",
        "glass-fill": "rgba(255, 255, 255, 0.7)",
        "error": "#ba1a1a",
        "outline-variant": "#bbc9cd",
        "tertiary-fixed-dim": "#ffb957",
        "surface-variant": "#dae2fd",
        "secondary-fixed": "#ffdbca",
        "inverse-surface": "#283044",
        "inverse-primary": "#2fd9f4",
        "background": "#faf8ff",
        "on-secondary-fixed": "#341100",
        "on-secondary-fixed-variant": "#783200",
        "on-primary-fixed-variant": "#004e5a",
        "primary-container": "#22d3ee",
        "surface-muted": "#F1F5F9",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#643f00",
        "secondary-fixed-dim": "#ffb690",
        "on-surface-variant": "#3c494c",
        "tertiary-fixed": "#ffddb5",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "on-primary-container": "#005763",
        "surface-container-highest": "#dae2fd",
        "on-secondary-container": "#5c2400",
        "on-tertiary-fixed": "#2a1800",
        "on-primary-fixed": "#001f25",
        "primary-fixed": "#a2eeff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#6e4600",
        "inverse-on-surface": "#eef0ff",
        "surface": "#faf8ff",
        "secondary": "#9d4300"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
